### ISSUE TITLE
Awesome Project. Open Source?

### ISSUE THREAD

**Issue by Ezra-Black** [tobikuyo/PressPlay#1]
Hey Tobi! Nice work. Haven't spoke to you in a while. Are you planning to open source this?

**Comment by tobikuyo** [comment]
Thank you Ezra. I wasn't really planning to, but I just might 🤔

**Comment by Ezra-Black** [comment]
You should contact me some time on Twitter @ezra_black_ I have been meaning to get ahold of you for some projects!
